User can turn their car
eniolajohnson/driving-game pull request #9
Opened 2020-12-12 19:59 UTC by eniolajohnson

![image](https://user-images.githubusercontent.com/73314663/101993689-d29db080-3cbc-11eb-9d80-ce5837aec83f.png)

2020-12-12 20:03 UTC, uzair-ashraf requested changes

2020-12-12 20:03 UTC, uzair-ashraf commented on main.js
> +  }
not needed

2020-12-12 20:03 UTC, uzair-ashraf commented on main.js
> +}
this kind of doesnt' really work as a data model
You could have a direction property which stores the direction?
`direction: 'east'`

2020-12-12 20:32 UTC, eniolajohnson commented on main.js
> +  }
Alright, will edit.

2020-12-12 20:48 UTC, eniolajohnson commented
![image](https://user-images.githubusercontent.com/73314663/101994584-b9e4c900-3cc3-11eb-8d7f-37626bca8257.png)

2020-12-13 13:42 UTC, eniolajohnson commented
Fixed it.

2020-12-13 13:42 UTC, eniolajohnson commented
![image](https://user-images.githubusercontent.com/73314663/102013584-746edd00-3d51-11eb-9642-0958858d9b33.png)

2021-01-05 23:53 UTC, Zhiwutian approved these changes
👍

2021-01-09 13:58 UTC, merged